BookChangeApp/Models/ErrorViewModel.cs
namespace BookChangeApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

BookChangeApp/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace BookChangeApp.Controllers
{
    public class ContactController : Controller
    {
        private readonly ILogger<ContactController> _logger;

        public ContactController(ILogger<ContactController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

BookChangeApp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using BookChangeApp.Models;

namespace BookChangeApp.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult BookSlider()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

BookChangeApp/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

namespace Namespace
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Signup()
        {
            return View();
        }
        
        
    }
}

BookChangeApp/Views/Contact/Index.cshtml
@{
    Layout = ViewBag.logg ? "_Layout" : "_LayoutUnregistered";
}
<div class="row mb-5 mx-4">
    <div id="form-title" class="mt-4">
        <h4 class="mx-2">Nos encantaria saber su opinion!</h4>
    </div>
    <div class="col-12 col-md-8 offset-md-2 col-xl-6 offset-xl-3">
        <form class="form-contacts">
            <div class="form-group my-4">
                <input type="text" class="form-control" id="nombre-apellido" aria-describedby="emailHelp"
                    placeholder="Nombre y Apellido *" />
            </div>
            <div class="form-group my-4">
                <input type="email" class="form-control" id="email" aria-describedby="emailHelp"
                    placeholder="Email *" />
            </div>
            <div class="form-group my-4">
                <input type="text" class="form-control" id="asunto" aria-describedby="emailHelp" placeholder="Asunto" />
            </div>
            <div class="form-group my-4">
                <textarea class="form-control" id="mensaje" rows="7" placeholder="Mensaje *"></textarea>
            </div>
            <button type="submit" class="btn btn-primary btn-lg btn-block">
                Enviar
            </button>
        </form>
    </div>
</div>

BookChangeApp/Views/Home/BookSlider.cshtml
<div id='carouselExampleControls' class='carousel slide' data-bs-ride='carousel'>
    <div class='carousel-inner' id='carousel-container'>
        <div class='carousel-item active'>
            <img src="~/img/books/libro1.jpg" class='d-block w-100' />
        </div>
        <div class='carousel-item'>
            <img src="~/img/books/libro2.jpg" class='d-block w-100' />
        </div>
        <div class='carousel-item'>
            <img src="~/img/books/libro3.jpg" class='d-block w-100' />
        </div>
        <div class='carousel-item'>
            <img src="~/img/books/libro4.jpg" class='d-block w-100' />
        </div>
    </div>
    <button class='carousel-control-prev' type='button' data-bs-target='#carouselExampleControls'
        data-bs-slide='prev'>
        <span class='carousel-control-prev-icon' aria-hidden='true'></span>
        <span class='visually-hidden'>Previous</span>
    </button>

    <button class='carousel-control-next' type='button' data-bs-target='#carouselExampleControls'
        data-bs-slide='next'>
        <span class='carousel-control-next-icon' aria-hidden='true'></span>
        <span class='visually-hidden'>Next</span>
    </button>
</div>

BookChangeApp/Views/Home/Card.cshtml
<div>
    <div class='card' style="width: 18rem" id='book-8'>
        <div class="id-6">
            <img src="~/img/books/libro6.jpg" class='card-img-top' height='350' />
        </div>

        <div class='card-body' style="padding-bottom: -15px">
            <div class="id-1">
                <h5 class='card-title mb-5' style="max-height: 24px">
                    ESCUELA DE TRADING
                </h5>
                <hr class='mx-2' />

                <p class='card-text'>
                <div class='pb-1'>
                    <strong>Para: </strong>
                    Vender
                </div>
                <div class='py-2'>
                    <strong>Precio: </strong>
                    25.000 Gs.
                </div>
                <strong class="text-success d-block"></strong>
                </p>
            </div>

            <button type='button' class="btn btn-primary btn-lg btn-block w-100 btn-contact">
                Obtener Libro
            </button>

            <section class='mt-3'>
                <span>
                    <img src="~/img/avatar.svg" alt='Avatar' title="Usuario" class='avatar' width='10' />
                </span>
                <span class='text-dark float-end pt-2 pr-3'>
                    <img src="~/img/bookmark.svg" title='Agregar como favorito' class='favourite' width='35' />
                </span>
            </section>
        </div>
    </div>
</div>

BookChangeApp/Views/Home/Index.cshtml
@{
    Layout = ViewBag.loggedIn ? "_Layout" : "_LayoutUnregistered";
}

 @Html.Partial("BookSlider.cshtml")

<div class="row bg-light my-5" id="others">
    @Html.Partial("~/Views/Shared/_TitleSection.cshtml")
    @for (int i = 0; i < 12; i++)
    {

        <div class="col-10 offset-2 col-sm-9 offset-sm-3 col-md-5 offset-md-1 col-xl-3 offset-xl-0 py-3">
            @Html.Partial("Card.cshtml")
        </div>
    } 

</div>

BookChangeApp/Views/Login/Index.cshtml
@{
    Layout = "_LayoutLogin";
}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="row m-3">
                <div class="col-md-12">
                    <div class="mx-auto text-center">
                        <a class="navbar-brand" href="#" title="Inicio">
                            <img src={book} alt="" width="50" />
                        </a>
                        <h3>Change Books</h3>
                    </div>
                </div>
            </div>

            <form class="border border-secondary p-4">
                <div class="form-group py-2">
                    <label for="emailValue" class="font-weight-bold">
                        Correo
                    </label>
                    <input type="emailValue" class="form-control" id="emailValue" aria-describedby="emailValueHelp"
                        autoComplete="disabled" />
                </div>
                <div class="form-group py-2">
                    <label for="password" class="font-weight-bold">
                        Contraseña
                    </label>
                    <input type="password" class="form-control" id="password" />
                </div>
                <button type="submit" class="btn btn-dark text-ligth btn-lg btn-block " id="btn-submit">
                    Iniciar Sesión
                </button>

                <hr class="line-horizontal my-5" />
                <div class="mt-4">
                    <small id="emailValueHelp" class="form-text text-muted d-flex justify-content-center">
                        ¿Eres nuevo por aqui? &nbsp; <br />
                        <a asp-controller="Login" asp-action="Signup">Cree su cuenta en Change Books</a>
                    </small>
                </div>
            </form>
            <!--div
                            class={
                                alert === ""
                                    ? "alert alert-danger my-5 text-center d-none"
                                    : "alert alert-danger my-5 text-center"
                            }
                            role="alert"
                        >
                            {alert}
                        </div-->
        </div>
        <div class="col-md-4"></div>
    </div>
</div>

BookChangeApp/Views/Login/Signup.cshtml
@{
    Layout = "_LayoutLogin";
}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="row m-3">
                <div class="col-md-12">
                    <div class="mx-auto text-center">
                        <a class="navbar-brand" href="#" title="Inicio">
                            <img src={book} alt="" width="50" />
                        </a>
                        <h3>Change Books</h3>
                    </div>
                </div>
            </div>

            <div class="border border-dark p-4">
                <div class="form-group py-2">
                    <label for="name" class="font-weight-bold">
                        Nombre
                    </label>
                    <input type="text" class="form-control" id="name" aria-describedby="emailHelp"
                        autoComplete="disabled" placeholder="Juan Perez" />
                </div>
                <div class="form-group py-2">
                    <label for="email" class="font-weight-bold">
                        Correo
                    </label>
                    <input type="email" class="form-control" id="email" aria-describedby="emailHelp"
                        autoComplete="disabled" placeholder="juanperez123@gmail.com" />
                </div>
                <div class="form-group py-2">
                    <label for="phone" class="font-weight-bold">
                        Número de telefono
                    </label>
                    <input type="tel" class="form-control" id="phone" aria-describedby="emailHelp"
                        autoComplete="disabled" placeholder="0981123456" maxLength="10" />
                </div>
                <div class="form-group py-2">
                    <label for="password" class="font-weight-bold">
                        Contraseña
                    </label>
                    <input type="password" class="form-control" id="password" />
                </div>
                <div class="form-group py-2 pb-3">
                    <label for="confirm-password" class="font-weight-bold">
                        Confirmar Contraseña
                    </label>
                    <input type="password" class="form-control" id="confirm-password" />
                </div>
                <button type="button" class="btn btn-dark text-ligth btn-lg btn-block">
                    Continuar
                </button>

                <!--div class="alert alert-danger mt-4 text-center" style={!warning ? { display: "none" } : {}}
                    role="alert">
                    {warning}
                </div-->

                <div class="mt-4">
                    <small id="emailHelp" class="form-text text-muted">
                        Al crear una cuenta, acepta las
                        <a href="">
                            Condiciones de uso y el Aviso de privacidad
                        </a>
                        de Book Changes.
                    </small>
                </div>

                <hr class="line-horizontal my-5" />
                <div class="mt-4">
                    <small id="emailHelp" class="form-text text-muted d-flex justify-content-center">
                        Ya tienes una cuenta &nbsp;
                        <a asp-controller="Login" asp-action="Index">Inicia Sesión</a>
                    </small>
                </div>
            </div>
        </div>
        <div class="col-md-4"></div>
    </div>
</div>

BookChangeApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookChangeApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
</head>

<body>
    <header id="home">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">

                <a class="navbar-brand" href="#" title="Inicio">
                    <img src="~/img/book.png" alt="" width="50" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" id="home-item" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Libros
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>
                                    <a class="dropdown-item" id="highlighted-item" href="#destacados">Destacados</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" id="recent-item" href="#recientes">Recientes</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" id="others-item" href="#otros">Otros</a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="contacts-item" asp-controller="Contact" asp-action="Index">Contactos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="my-book-item" href="./views/myBooks.html">Mis Libros</a>
                        </li>

                        <li class="nav-item dropdown users-details" id="users-details">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Perfil
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>
                                    <a class="dropdown-item" id="my-profile-item">Mi Perfil</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" id="favourite-item">Favoritos</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" id="messages-item">Mensajes</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" id="others-item" href="#otros">Cerrar Sesion</a>
                                </li>
                            </ul>
                        </li>
                    </ul>

                    <form class="d-flex ">
                        <input class="form-control me-2" type="search" id="search" placeholder="Buscar"
                            aria-label="Search" />
                        <button class="btn btn-outline-success" type="button" id="btn-search">
                            Buscar
                        </button>
                    </form>

                    <div class="icon-users">
                        <span class="mx-3">
                            <a href="./views/favorites.html" id="favorites-item" title="Favoritos">
                                <img src="~/img/wish_list.svg" width="30" alt="" />
                            </a>
                        </span>

                        <span class="mx-3">
                            <a href="./views/messages.html" id="messages-item" title="Mensajes">
                                <img src="~/img/message.svg" width="30" alt="" />
                            </a>
                        </span>

                        <span class="mx-1 dropdown">
                            <div class="dropdown" style="float: left">
                                <a href="" class="dropbtn" id="my-profile-item" title="Mi Perfil">
                                    <img src="~/img/user.svg" width="30" alt="" />
                                </a>
                                <div class="dropdown-content" id="profile-option">
                                    <a href="#">Mi Perfil</a>
                                    <a href="#">Cerrar Sesion</a>
                                </div>
                            </div>
                        </span>
                    </div>

                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>


        <div class="row">
            <div class="col-md-12">
                <div class="container">
                    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
                        <div class="col-md-4 d-flex align-items-center">
                            <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                                <svg class="bi" width="30" height="24">
                                    <use xlink:href="#bootstrap" />
                                </svg>
                            </a>
                            <span class="text-muted">&copy; 2023 Company, Inc</span>
                        </div>

                        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                            <li class="ms-3">
                                <a class="text-muted" href="#">
                                    <img src="~/img/facebook.svg" alt="" width="24" srcset="" />
                                </a>
                            </li>
                            <li class="ms-3">
                                <a class="text-muted" href="#">
                                    <img src="~/img/instagram.svg" alt="" width="24" srcset="" />
                                </a>
                            </li>
                            <li class="ms-3">
                                <a class="text-muted" href="#">
                                    <img src="~/img/twitter.svg" alt="" width="24" srcset="" />
                                </a>
                            </li>
                        </ul>
                    </footer>
                </div>
            </div>
        </div>

    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

BookChangeApp/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookChangeApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
</head>

<body>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

BookChangeApp/Views/Shared/_LayoutUnregistered.cshtml
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookChangeApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
</head>

<body>
    <header id="home">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">

                <a class="navbar-brand" href="#" title="Inicio">
                    <img src="~/img/book.png" alt="" width="50" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" id="home-item" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Libros
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>
                                    <a class="dropdown-item" id="highlighted-item" href="#destacados">Destacados</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" id="recent-item" href="#recientes">Recientes</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" id="others-item" href="#otros">Otros</a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="contacts-item" asp-controller="Contact" asp-action="Index">Contactos</a>
                        </li>
                    </ul>

                    <form class="d-flex ">
                        <input class="form-control me-2" type="search" id="search" placeholder="Buscar"
                            aria-label="Search" />
                        <button class="btn btn-outline-success" type="button" id="btn-search">
                            Buscar
                        </button>
                    </form>

                    <div class="icon-users">
                        

                        <span class="mx-1 dropdown">
                            <div class="dropdown" style="float: left">
                                <a class="dropbtn" id="my-profile-item" title="Iniciar Sesión" asp-controller="Login" asp-action="Index">
                                    <img src="~/img/user.svg" width="30" alt="" />
                                </a>
                            </div>
                        </span>
                    </div>

                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>


        <div class="row">
            <div class="col-md-12">
                <div class="container">
                    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
                        <div class="col-md-4 d-flex align-items-center">
                            <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                                <svg class="bi" width="30" height="24">
                                    <use xlink:href="#bootstrap" />
                                </svg>
                            </a>
                            <span class="text-muted">&copy; 2023 Company, Inc</span>
                        </div>

                        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                            <li class="ms-3">
                                <a class="text-muted" href="#">
                                    <img src="~/img/facebook.svg" alt="" width="24" srcset="" />
                                </a>
                            </li>
                            <li class="ms-3">
                                <a class="text-muted" href="#">
                                    <img src="~/img/instagram.svg" alt="" width="24" srcset="" />
                                </a>
                            </li>
                            <li class="ms-3">
                                <a class="text-muted" href="#">
                                    <img src="~/img/twitter.svg" alt="" width="24" srcset="" />
                                </a>
                            </li>
                        </ul>
                    </footer>
                </div>
            </div>
        </div>

    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

BookChangeApp/Views/Shared/_TitleSection.cshtml
<div id="other">
    <div class='row'>
        <div class="col-6 offset-0 col-md-3 offset-md-1 pt-2">
            <h5 id='recientes'>Lo mas destacado</h5>
        </div>
        <div class='row'>
        </div>
    </div>
</div>